{{- if gt (len .Values.application.ingress.hosts) 0 }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-application
  annotations:
{{ toYaml .Values.application.ingress.annotations | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: application
spec:
{{- if gt (len .Values.application.ingress.tls) 0 }}
  tls:
  {{- range .Values.application.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $host := .Values.application.ingress.hosts }}
  {{- $url := splitList "/" $host }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: "{{ printf "%s-application" (include "fullname" $) }}"
              servicePort: http
  {{- end}}
{{- end }}
