version: '3.7'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: ['nodemon', '.']
    depends_on:
      - db
      - jaeger
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JAEGER_AGENT_HOST=jaeger
      - MONGODB_HOST=db
      - MONGODB_USERNAME=username
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=spotguide-nodejs-mongodb
      - MONGODB_AUTH_SOURCE=admin
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./web
        target: /home/node/web
        read_only: true

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ['CMD', 'mongo', '--eval', '{ ping: 1 }']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=spotguide-nodejs-mongodb

  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
