{
 "title": "Application",
 "tags": [
  "Node.js",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "image",
    "label": "Image",
    "query": "label_values(nodejs_version_info, image)"
   },
   {
    "name": "name",
    "label": "Pod name",
    "query": "label_values(nodejs_version_info, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Server Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{status_code=~\"^5..$\",image=~\"$image\",name=~\"$name\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{image=~\"$image\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps", "label": "request/sec" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{path!=\"/healthy\",path!=\"/ready\",image=~\"$image\",name=~\"$name\"}[$__interval])) by (method, path, status_code) / 60",
     "legendFormat": "{{method}} {{path}} | {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Error Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{status_code=~\"^5..$\",image=~\"$image\",name=~\"$name\"}[$__interval])) by (method,path) / sum(increase(http_request_duration_ms_count{image=~\"$image\",name=~\"$name\"}[$__interval])) by (method,path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket{image=~\"$image\",name=~\"$name\"}[$__interval])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Node.js Event Loop Lag",
   "type": "graph",
   "description": "Lag of event loop in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nodejs_eventloop_lag_seconds{image=~\"$image\",name=~\"$name\"}[$__interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(process_cpu_seconds_total{image=~\"$image\",name=~\"$name\"}[$__interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{image=~\"$image\",name=~\"$name\"} / 1024^2) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}