defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

workflows:
  version: 2
  test:
    jobs:
      - test
