defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build_and_deploy:
    docker:
      - image: gcr.io/k8s-skaffold/skaffold:v0.24.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: |
          go get -u sigs.k8s.io/kind
          kind create cluster
          export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
          cd .banzaicloud
          skaffold config set --global local-cluster true
          skaffold run
      - save_cache:
          key: v1-pkg-cache
          paths:
            - '/go/pkg'

workflows:
  version: 2
  test:
    jobs:
      - test
      - build_and_deploy
