dependencies:
- name: pipeline-cluster-monitor
  repository: http://kubernetes-charts.banzaicloud.com/branch/master
  version: '>=0.1.17'
  alias: monitor
  condition: monitor.enabled
- name: pipeline-cluster-ingress
  repository: http://kubernetes-charts.banzaicloud.com/branch/master
  version: '>=0.0.6'
  alias: ingress
  condition: ingress.enabled
- name: mongodb
  # repository: '@stable'
  repository: "file://../mongodb"
  version: 5.1.0
  alias: mongodb
  condition: mongodb.enabled
