dependencies:
- name: pipeline-cluster-monitor
  repository: https://kubernetes-charts.banzaicloud.com
  version: '>=0.1.17'
  alias: pipeline-monitor
  condition: pipeline-monitor.enabled
- name: pipeline-cluster-ingress
  repository: https://kubernetes-charts.banzaicloud.com
  version: '>=0.0.8'
  alias: pipeline-ingress
  condition: pipeline-ingress.enabled
- name: mongodb
  repository: "file://../mongodb"
  version: 5.1.0
  alias: mongodb
  condition: mongodb.enabled
